=== lewisl/epi_sim/utility/vax-schedule.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/Welcome",
    "definitions": {
        "Welcome": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "vaxesincluded": {
                    "$ref": "#/definitions/Vaxesincluded"
                },
                "dayrange": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "targetpct": {
                    "type": "number"
                },
                "filtervec": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "shotmode": {
                    "type": "string"
                },
                "pattern": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "spreadfunc": {
                    "type": "null"
                }
            },
            "required": [
                "dayrange",
                "filtervec",
                "pattern",
                "shotmode",
                "spreadfunc",
                "targetpct",
                "vaxesincluded"
            ],
            "title": "Welcome"
        },
        "Vaxesincluded": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "Pfizer": {
                    "$ref": "#/definitions/JnJ"
                },
                "Moderna": {
                    "$ref": "#/definitions/JnJ"
                },
                "JnJ": {
                    "$ref": "#/definitions/JnJ"
                }
            },
            "required": [
                "JnJ",
                "Moderna",
                "Pfizer"
            ],
            "title": "Vaxesincluded"
        },
        "JnJ": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "mix": {
                    "type": "number"
                },
                "starting_doses": {
                    "type": "integer"
                },
                "pct2ndshot": {
                    "type": "number"
                },
                "pctboost": {
                    "type": "number"
                },
                "alternate": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            },
            "required": [
                "alternate",
                "mix",
                "pct2ndshot",
                "pctboost",
                "starting_doses"
            ],
            "title": "JnJ"
        }
    }
}

=== lewisl/epi_sim/sample_parameters/vaccine_100k fast/loc38015_old.json
{
    "vaxesincluded": {
        "Pfizer": {
            "mix": 0.5,
            "starting_doses": 40000,
            "pct2ndshot": 0.9,
            "pctboost": 0.6,
            "alternate": [
                "Moderna",
                "JnJ"
            ]
        },
        "Moderna": {
            "mix": 0.45,
            "starting_doses": 36000,
            "pct2ndshot": 0.9,
            "pctboost": 0.6,
            "alternate": [
                "Pfizer",
                "JnJ"
            ]
        },
        "JnJ": {
            "mix": 0.05,
            "starting_doses": 4000,
            "pct2ndshot": 0,
            "pctboost": 0.4,
            "alternate": [
                "Pfizer",
                "Moderna"
            ]
        }
    },
    "dayrange": [
        150,
        250
    ],
    "targetpct": 0.95,
    "filtervec": [
        "age80_up",
        "age60_79"
    ],
    "shotmode": "all",
    "pattern": [
        0,
        0.02,
        0.05,
        0.1,
        0.15,
        0.19,
        0.21,
        0.16,
        0.08,
        0.03,
        0.01,
        0
    ],
    "spreadfunc": null
}
